# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EuS2Filmes' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EuS2Filmes
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Kingfisher'

  target 'EuS2FilmesTests' do
    inherit! :search_paths
    # Pods for testing

    pod 'Quick'
    pod 'Nimble'
  end

  target 'EuS2FilmesUITests' do
    inherit! :search_paths
    # Pods for testing

    pod 'Quick'
    pod 'Nimble'
    
  end

end
